### PR TITLE
Add tcp.txt

### PR DESCRIPTION
**Pull request by Vic-Soft**
This will fix the bug on line #4567

### CODE REVIEW

**Comment by Vic-Soft** [comment]
@Chibuike-Mba, please attend to this review as soon as possible because we are approaching deadline.

**Review by Chibuike-Mba — CHANGES_REQUESTED** [review]
Change the content of the tcp.txt file to reflect the latest implementation on the last commit.

**Comment by Vic-Soft** [comment]
ok, on it now

**Review by Chibuike-Mba — COMMENTED** [review]
That's a great job right there.

**Review by Chibuike-Mba — APPROVED** [review]
You can now merge the branch. 
Thank you.

**Pull request merged**
